/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MovieSchedule } from '../../models/movie-schedule';

export interface CreateSchedule$Params {
  
    /**
     * MovieSchedule object that needs to be created
     */
    body: MovieSchedule
}

export function createSchedule(http: HttpClient, rootUrl: string, params: CreateSchedule$Params, context?: HttpContext): Observable<StrictHttpResponse<MovieSchedule>> {
  const rb = new RequestBuilder(rootUrl, createSchedule.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MovieSchedule>;
    })
  );
}

createSchedule.PATH = '/api/schedules';
