/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Error response
 */
export interface Error {

  /**
   * Error code
   */
  code?: number;

  /**
   * Error message
   */
  message?: string;
}
