/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * JWT token response
 */
export interface JwtResponse {

  /**
   * JWT token
   */
  token?: string;
}
