/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * User credentials for authentication
 */
export interface LoginRequest {

  /**
   * The password of the user
   */
  password: string;

  /**
   * The username of the user
   */
  username: string;
}
