/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * A movie entity
 */
export interface Movie {

  /**
   * Brief description of the movie
   */
  description?: string;

  /**
   * Unique identifier for the movie
   */
  id?: number;

  /**
   * Title of the movie
   */
  title: string;
}
