/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { authenticateUser } from '../fn/authentication/authenticate-user';
import { AuthenticateUser$Params } from '../fn/authentication/authenticate-user';
import { JwtResponse } from '../models/jwt-response';


/**
 * Endpoints for user authentication
 */
@Injectable({ providedIn: 'root' })
export class AuthenticationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `authenticateUser()` */
  static readonly AuthenticateUserPath = '/api/auth/login';

  /**
   * Authenticate user.
   *
   * Generates a JWT token for the user based on credentials.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `authenticateUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authenticateUser$Response(params: AuthenticateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<JwtResponse>> {
    return authenticateUser(this.http, this.rootUrl, params, context);
  }

  /**
   * Authenticate user.
   *
   * Generates a JWT token for the user based on credentials.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `authenticateUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  authenticateUser(params: AuthenticateUser$Params, context?: HttpContext): Observable<JwtResponse> {
    return this.authenticateUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<JwtResponse>): JwtResponse => r.body)
    );
  }

}
